name: Build and Deploy Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for AWS OIDC
      contents: read # Required to checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21' # Adjust if needed, but 1.21 is a recent LTS

      - name: Install dependencies
        run: go mod download

      - name: Run tests # NEW STEP
        run: make test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} # Store your IAM Role ARN in GitHub Secrets
          aws-region: ${{ secrets.AWS_REGION }} # Store your AWS Region in GitHub Secrets

      - name: Build Lambda
        run: make build

      # Note: Actual deployment should only run on merge to main, not on PRs.
      # This example deploys on every push to main.
      # Consider adding a condition: if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - name: Deploy Lambda
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make deploy
